export const CAPABILITY_REGISTRY = [
  { key: "intent-to-product", sourceTrack: "Base44", capability: "Intent to working product", canonical: "ResellerPro", implementation: "bounded product/workspace workflows" },
  { key: "visual-first", sourceTrack: "Lovable", capability: "Visual-first product creation", canonical: "MindReply", implementation: "owner-controlled visual/product surface" },
  { key: "live-preview", sourceTrack: "Bolt.new", capability: "Live preview", canonical: "MindReply", implementation: "preview and independent runtime verification" },
  { key: "agentic-engineering", sourceTrack: "Replit Agent", capability: "Agentic engineering execution", canonical: "A11-K", implementation: "bounded execution contracts" },
  { key: "github-native", sourceTrack: "Cursor", capability: "GitHub-native ownership", canonical: "A11-K", implementation: "canonical repository and branch evidence" },
  { key: "full-stack-generation", sourceTrack: "v0", capability: "Full-stack generation", canonical: "ResellerPro", implementation: "Next.js runtime + API + persistence" },
  { key: "visual-code-control", sourceTrack: "Bubble", capability: "Visual editing without losing code control", canonical: "MindReply", implementation: "product surface backed by canonical source" },
  { key: "automatic-qa", sourceTrack: "Emergent", capability: "Automatic QA", canonical: "agent-control-plane", implementation: "test/build/health/evidence gates" },
  { key: "proof-artifacts", sourceTrack: "Emergent", capability: "Proof/evidence artifacts", canonical: "agent-control-plane", implementation: "evidence receipts" },
  { key: "design-system-memory", sourceTrack: "Lovable", capability: "Design-system memory", canonical: "MindReply", implementation: "canonical visual system" },
  { key: "controlled-deployment", sourceTrack: "Replit Agent", capability: "Controlled deployment", canonical: "ResellerPro", implementation: "Cloudflare/OpenNext release path" },
  { key: "version-rollback", sourceTrack: "Cursor", capability: "Versioning and rollback", canonical: "A11-K", implementation: "Git branch/commit release identity" },
  { key: "integrations", sourceTrack: "Base44", capability: "First-class integrations", canonical: "ResellerPro", implementation: "provider adapters and explicit credentials" },
  { key: "parallel-execution", sourceTrack: "Cursor", capability: "Parallel bounded execution", canonical: "agent-control-plane", implementation: "bounded task contracts" },
  { key: "owner-control", sourceTrack: "Bubble", capability: "Owner approval/control", canonical: "agent-control-plane", implementation: "approval and audit boundaries" },
  { key: "mobile-first", sourceTrack: "Lovable", capability: "Mobile/iPhone-first operation", canonical: "MindReply", implementation: "responsive owner/product surfaces" },
  { key: "idea-to-evidence-loop", sourceTrack: "Replit Agent", capability: "Idea → visual → implementation → test → deploy → verify → evidence → iterate", canonical: "agent-control-plane", implementation: "cross-repository release contract" },

  { key: "enterprise-ai-ml", sourceTrack: "Enterprise", capability: "Artificial Intelligence & Machine Learning", canonical: "ResellerPro", implementation: "use-case evaluation, human review, measured model evidence and rollback controls" },
  { key: "enterprise-data-analytics", sourceTrack: "Enterprise", capability: "Data & Analytics", canonical: "ResellerPro", implementation: "data quality, lineage, metric definitions and decision-ready reporting" },
  { key: "enterprise-it-infrastructure-modernisation", sourceTrack: "Enterprise", capability: "IT Infrastructure Modernisation", canonical: "ResellerPro", implementation: "workload inventory, resilience baseline, migration waves and recovery evidence" },
  { key: "enterprise-application-modernisation-development", sourceTrack: "Enterprise", capability: "Application Modernisation & Development", canonical: "ResellerPro", implementation: "incremental application changes, integration contracts, tests and rollback evidence" },
  { key: "enterprise-security", sourceTrack: "Enterprise", capability: "Security", canonical: "ResellerPro", implementation: "identity-first access, secure development, incident readiness and retested controls" },
  { key: "enterprise-managed-services", sourceTrack: "Enterprise", capability: "Managed Services", canonical: "ResellerPro", implementation: "service ownership, health/error signals, incident handling and reviewable change" },
  { key: "enterprise-digital-workplace", sourceTrack: "Enterprise", capability: "Digital Workplace", canonical: "ResellerPro", implementation: "collaboration, identity, device posture and usable operational workflows" },
  { key: "enterprise-training", sourceTrack: "Enterprise", capability: "Training & Enablement", canonical: "ResellerPro", implementation: "role-based learning, incident exercises, runbooks and handover acceptance" },
] as const;

export type CapabilityKey = (typeof CAPABILITY_REGISTRY)[number]["key"];
